number1 = input("Enter number: ")
print(id(number1))
number2 = input("Enter number: ")
print(id(number2))
float(number1)
print(id(number2))
float(number2)
print(type(number1))
print(id(number2))
print(number1 + number2)